services:
  postgres:
    image: postgres:16
    container_name: pg_local
    environment:
      POSTGRES_USER: yana
      POSTGRES_PASSWORD: 1147
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yana -d bookstore"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

volumes:
  pg_data:
